msg=[
	 "Welcome EmoteMaker Online V2 RC1",
	 "Create a new emote",
	 "Save the current emote to your computer",
	 "Some usefull link's",
	 "Show faces tab",
	 "Show eyes tab",
	 "Show mouths tab",
	 "Set size of emote to Width:20 Height:20",
	 "Set size of emote to Width:40 Height:40",
	 "Select a custum size",
	 "Make a random Emoticon",
	 "Move Up",
	 "Move Left",
	 "Move Center",
	 "Move Right",
	 "Move Down",
	 "Speed Up",
	 "Current Speed",
	 "Speed Down",
	 "Face moveable or not",
	 "Eye moveable or not",
	 "Mouth moveable or not",
	 "Counter, count how many times this page was lunched"
	 ]